In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"C:\Users\HP\DATA_SCIENCE\Projects\Credit Risk Scoring\Data\credit_risk_dataset.csv")

df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [3]:
# Data Validation
df = df.drop_duplicates()

df = df[df["person_age"] >= 18]
df = df[df["person_age"] <= 100]
df = df[df["person_income"] > 0]
df = df[df["loan_amnt"] > 0]
df = df[df["loan_int_rate"] >= 0]

df.shape

(29317, 12)

In [4]:
df.isnull().sum()

person_age                      0
person_income                   0
person_home_ownership           0
person_emp_length             820
loan_intent                     0
loan_grade                      0
loan_amnt                       0
loan_int_rate                   0
loan_status                     0
loan_percent_income             0
cb_person_default_on_file       0
cb_person_cred_hist_length      0
dtype: int64

In [5]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
cat_cols = df.select_dtypes(include=["object"]).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [6]:
df["loan_to_income_ratio"] = df["loan_amnt"] / df["person_income"]

In [7]:
df["income_band"] = pd.cut(
    df["person_income"],
    bins=[0, 30000, 70000, 150000, float("inf")],
    labels=["Low", "Medium", "High", "Very High"]
)

In [8]:
df["age_group"] = pd.cut(
    df["person_age"],
    bins=[18, 25, 35, 50, 100],
    labels=["Young", "Adult", "Middle Age", "Senior"]
)

In [9]:
df["high_interest_flag"] = (df["loan_int_rate"] > 15).astype(int)

In [10]:
df["high_loan_burden"] = (df["loan_percent_income"] > 0.30).astype(int)

In [11]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_to_income_ratio,income_band,age_group,high_interest_flag,high_loan_burden
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,0.593220,Medium,Young,1,1
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0.104167,Low,Young,0,0
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,0.572917,Low,Young,0,1
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,0.534351,Medium,Young,1,1
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,0.643382,Medium,Young,0,1

In [ ]:
df.to_csv("../Data/credit_risk_processed.csv", index=False)
#  NOTEBOOK INSIDE ANOTHER FOLDER